
spring:
  application:
    name: siga-saas-api

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.project: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"